name: 'GitHub Actions Weather Bot'

on:
  push:
  schedule:
    - cron: '42 19 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Weather'
        run: bash ./weather.sh
      - name: 'Get Date'
        run: echo "::set-env name=REPORT_DATE::$(TZ=':Asia/Shanghai' date '+%Y-%m-%d')"
      - name: Sending message
        uses: yakumioto/serverchan-action@v1
        with:
          key: ${{ secrets.sckey }}
          text: 深圳天气预报 ${{env.REPORT_DATE}}
          desp: file://result.html
